name: Lint title

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  validate-title:
    name: Validate Pull Request Title
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          # Configure which types are allowed (newline-delimited).
          # Default: https://github.com/commitizen/conventional-commit-types
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
          scopes: |
            core
            ui
            JIRA-\d+
          requireScope: false
          disallowScopes: |
            release
            [A-Z]+
